saveconfig-kanotix (0.5.21) unstable; urgency=low
  * re- indent.
  * fix mnt vs. media confusion, thanks to eco2geek.

diff --git a/saveconfig b/saveconfig
--- a/saveconfig
+++ b/saveconfig
@@ -21,10 +21,10 @@ export XDIALOG_HIGH_DIALOG_COMPAT
 
 TMP="/tmp/saveconfig.tmp$$"
 
-bailout(){
-rm -f "$TMP" "$TMP.done" "$TMP.err"
-umount "$DIRECTORY"
-exit 0
+bailout() {
+	rm -f "$TMP" "$TMP.done" "$TMP.err"
+	umount "$DIRECTORY"
+	exit 0
 }
 
 DIALOG="dialog"
@@ -42,45 +42,45 @@ DESKTOPKB="$(du -sk $HOME/Desktop 2>/dev/null | awk '{print $1}')"
 
 # Language-dependent Messages
 case "$LANGUAGE" in
-de*|at*|ch*)
-TITLE1="${FLL_DISTRO_NAME} Konfigurationsarchiv anlegen"
-MESSAGE1="Konfigurationsdateien auswählen:"
-MESSAGE2="Bitte legen Sie jetzt eine leere DOS- oder ext2-formatierte, schreibbare Diskette ein."
-MESSAGE3="Archiviere geänderte Konfigurationsdateien..."
-MESSAGE4="Bitte wählen Sie das Verzeichnis, in das Sie die Konfigurationsdateien schreiben wollen."
-E1="Persönliche Einstellungen (Desktop, Programme)"
-E2="Netzwerk Einstellungen (LAN, Modem, ISDN, ASDL)"
-E3="Grafik Subsystem Einstellungen (XF86Config)"
-E4="Weitere systemweite Einstellungen (Drucker etc.)"
-E5="Alle Desktop-Dateien (${DESKTOPKB}kB)"
-ERROR="Leider konnte die ${FLL_DISTRO_NAME}-Konfiguration NICHT gespeichert werden:"
-;;
-es*)
-TITLE1="Crear un archive de configuración de${FLL_DISTRO_NAME}"
-MESSAGE1="Elija el tipo de archivos de configuración:"
-MESSAGE2="Por favor, inserte un disquete vacío escribible formateado para DOS o ext2."
-MESSAGE3="Grabando archivos de la configuración..."
-MESSAGE4="Por favor, seleccione el directorio para los archivos de la configuración del ahorro."
-E1="Configuración personal (escritorio, programas)"
-E2="Configuración de Red (LAN, Modem, RDSI, ADSL)"
-E3="Configuración del subsistema gráfico (XF86Config)"
-E4="Otras configuraciones del sistema (impresora, etc.)"
-E5="Todos los archivos en el Escritorio (${DESKTOPKB}kB)"
-ERROR="No se pudo crear de configuración de ${FLL_DISTRO_NAME}:"
-;;
-*)
-TITLE1="Create ${FLL_DISTRO_NAME} configuration archive"
-MESSAGE1="Chose type of configuration files:"
-MESSAGE2="Please insert an empty DOS- or ext2-formatted, writable floppy disk."
-MESSAGE3="Saving configuration archive..."
-MESSAGE4="Please select directory for saving configuration files:"
-E1="Personal configuration (desktop, programs)"
-E2="Network settings (LAN, Modem, ISDN, ADSL)"
-E3="Graphics subsystem settings (XF86Config)"
-E4="Other system configuration (printer etc.)"
-E5="All files on the Desktop (${DESKTOPKB}kB)"
-ERROR="The ${FLL_DISTRO_NAME} configuration could NOT be saved:"
-;;
+	de*|at*|ch*)
+		TITLE1="${FLL_DISTRO_NAME} Konfigurationsarchiv anlegen"
+		MESSAGE1="Konfigurationsdateien auswählen:"
+		MESSAGE2="Bitte legen Sie jetzt eine leere DOS- oder ext2-formatierte, schreibbare Diskette ein."
+		MESSAGE3="Archiviere geänderte Konfigurationsdateien..."
+		MESSAGE4="Bitte wählen Sie das Verzeichnis, in das Sie die Konfigurationsdateien schreiben wollen."
+		E1="Persönliche Einstellungen (Desktop, Programme)"
+		E2="Netzwerk Einstellungen (LAN, Modem, ISDN, ASDL)"
+		E3="Grafik Subsystem Einstellungen (XF86Config)"
+		E4="Weitere systemweite Einstellungen (Drucker etc.)"
+		E5="Alle Desktop-Dateien (${DESKTOPKB}kB)"
+		ERROR="Leider konnte die ${FLL_DISTRO_NAME}-Konfiguration NICHT gespeichert werden:"
+		;;
+	es*)
+		TITLE1="Crear un archive de configuración de${FLL_DISTRO_NAME}"
+		MESSAGE1="Elija el tipo de archivos de configuración:"
+		MESSAGE2="Por favor, inserte un disquete vacío escribible formateado para DOS o ext2."
+		MESSAGE3="Grabando archivos de la configuración..."
+		MESSAGE4="Por favor, seleccione el directorio para los archivos de la configuración del ahorro."
+		E1="Configuración personal (escritorio, programas)"
+		E2="Configuración de Red (LAN, Modem, RDSI, ADSL)"
+		E3="Configuración del subsistema gráfico (XF86Config)"
+		E4="Otras configuraciones del sistema (impresora, etc.)"
+		E5="Todos los archivos en el Escritorio (${DESKTOPKB}kB)"
+		ERROR="No se pudo crear de configuración de ${FLL_DISTRO_NAME}:"
+		;;
+	*)
+		TITLE1="Create ${FLL_DISTRO_NAME} configuration archive"
+		MESSAGE1="Chose type of configuration files:"
+		MESSAGE2="Please insert an empty DOS- or ext2-formatted, writable floppy disk."
+		MESSAGE3="Saving configuration archive..."
+		MESSAGE4="Please select directory for saving configuration files:"
+		E1="Personal configuration (desktop, programs)"
+		E2="Network settings (LAN, Modem, ISDN, ADSL)"
+		E3="Graphics subsystem settings (XF86Config)"
+		E4="Other system configuration (printer etc.)"
+		E5="All files on the Desktop (${DESKTOPKB}kB)"
+		ERROR="The ${FLL_DISTRO_NAME} configuration could NOT be saved:"
+		;;
 esac
 
 $DIALOG --clear --title "$TITLE1" --checklist "$MESSAGE1" 18 75 9 p "$E1" on d "$E5" off n "$E2" on x "$E3" on o "$E4" on 2>"$TMP" || bailout
@@ -95,28 +95,42 @@ CHOWNHOME=""
 NETFILES='/etc/network|/etc/ppp|/etc/chat|/etc/isdn|/etc/sysconfig/isdn|/etc/sysconfig/provider|/etc/resolv\.conf|/etc/hosts|/etc/hosts\.|/etc/inetd\.conf'
 XFILES='/etc/X11'
 for i in `sed 's,",,g;s,/, ,g;s,'\'',,g;' < "$TMP"`; do
-case $i in
-p) SAVEHOME="yes" ;;
-d) SAVEDESK="yes" ;;
-n|x|o) SAVEETC="yes"; case "$i" in n) SAVENET="yes";; x) SAVEX="yes";; esac ;;
-esac
+	case $i in
+		p)
+			SAVEHOME="yes"
+			;;
+		d)
+			SAVEDESK="yes"
+			;;
+		n|x|o)
+			SAVEETC="yes"
+			case "$i" in
+				n)
+					SAVENET="yes"
+					;;
+				x)
+					SAVEX="yes"
+					;;
+			esac
+			;;
+	esac
 done
 
 [ -n "$SAVEHOME" -o -n "$SAVEDESK" ] && CHOWNHOME="chown -R $(ls -ld $HOME | awk '{print $3"."$4}') $HOME"
 
 # Find changes in (real) files of dir1 ... dir2
-findchanged(){
-if [ -d "$1" ]; then
-for i in `( cd "$1"; find . -type f | sed 's,^\./,,g' | grep -v ' ' )`; do
-cmp -s "$1/$i" "$2/$i" || echo "$1/$i"
-done
-elif [ -e "$1" ]; then
-cmp -s "$1" "$2" || echo "$1"
-fi
+findchanged() {
+	if [ -d "$1" ]; then
+		for i in `( cd "$1"; find . -type f | sed 's,^\./,,g' | grep -v ' ' )`; do
+			cmp -s "$1/$i" "$2/$i" || echo "$1/$i"
+		done
+	elif [ -e "$1" ]; then
+		cmp -s "$1" "$2" || echo "$1"
+	fi
 }
 
-writescript(){
-cat >"$1" <<EOT
+writescript() {
+	cat >"$1" <<EOT
 #!/bin/sh
 [ "\`id -u\`" = "0" ] || { echo "You need root privileges to modify the system!" >&2 ; exit 1; }
 [ -d "\$1" ] && CONFIGS="\$1/configs.tbz"
@@ -128,19 +142,19 @@ tar -jpPtf "\$CONFIGS" | while read i; do rm -f "\$i"; done
 tar -jpPxf "\$CONFIGS" ; $CHOWNHOME
 fi
 EOT
-return "$?"
+	return "$?"
 }
 
 # Just displays the symlink target, does not actually cause the automounter to attempt starting a mount.
 FLOPPYDIR="$(ls -l /media/floppy0 | awk '{print $NF}')"
 
-umountfloppy(){
-mount | grep -q "$FLOPPYDIR" && umount "$FLOPPYDIR" 2>/dev/null
+umountfloppy() {
+	mount | grep -q "$FLOPPYDIR" && umount "$FLOPPYDIR" 2>/dev/null
 }
 
 # Directory selector
 PARTITIONS="/media/floppy0 [Floppy] on"
-for i in `awk '/^\/dev\/([hs]d|ub)[a-z].*\/mnt\/([hs]d|ub)[a-z]/{if(!/ntfs/){print $2}}' /etc/fstab`; do
+for i in `awk '/^\/dev\/([hs]d|ub)[a-z].*\/media\/([hs]d|ub)[a-z]/{if(!/ntfs/){print $2}}' /etc/fstab`; do
 PARTITIONS="$PARTITIONS ${i} [Disk/Partition] off"
 done
 
@@ -151,31 +165,34 @@ $DIALOG --clear --title "$TITLE1" --radiolist "$MESSAGE4" 18 75 9 $PARTITIONS 2>
 DIRECTORY="$(<$TMP)"
 [ -z "$DIRECTORY" -o ! -e "$DIRECTORY" ] && bailout
 
-case "$DIRECTORY" in *floppy*)
-DIRECTORY="$FLOPPYDIR"
-KNOPPIXSH="$DIRECTORY/knoppix.sh"
-while :; do
-umountfloppy
-$DIALOG --title "$TITLE1" --yesno "$MESSAGE2" 8 65 || bailout
-echo "$FLOPPYDIR" | grep -q auto || mount /media/floppy0
-[ "$?" = "0" ] && writescript "$KNOPPIXSH" && break
-done
-;;
-*)
-rm -f "$TMP.err"
-mount | grep -q "$DIRECTORY" || mount -r "$DIRECTORY" >"$TMP.err"
-[ "$?" != "0" ] && { $DIALOG --title "$TITLE1" --msgbox "$ERROR `cat $TMP.err`" 10 75; bailout; }
-mount | grep -q "$DIRECTORY.*ntfs" && { $DIALOG --title "$TITLE1" --msgbox "$ERROR NTFS" 10 75; bailout; }
-mount -o remount,rw "$DIRECTORY"
-KNOPPIXSH="$DIRECTORY/knoppix.sh"
-writescript "$KNOPPIXSH"
+case "$DIRECTORY" in 
+	*floppy*)
+		DIRECTORY="$FLOPPYDIR"
+		KNOPPIXSH="$DIRECTORY/knoppix.sh"
+		
+		while :; do
+			umountfloppy
+			$DIALOG --title "$TITLE1" --yesno "$MESSAGE2" 8 65 || bailout
+			echo "$FLOPPYDIR" | grep -q auto || mount /media/floppy0
+			[ "$?" = "0" ] && writescript "$KNOPPIXSH" && break
+		done
+		;;
+	*)
+		rm -f "$TMP.err"
+		mount | grep -q "$DIRECTORY" || mount -r "$DIRECTORY" >"$TMP.err"
+		[ "$?" != "0" ] && { $DIALOG --title "$TITLE1" --msgbox "$ERROR `cat $TMP.err`" 10 75; bailout; }
+		mount | grep -q "$DIRECTORY.*ntfs" && { $DIALOG --title "$TITLE1" --msgbox "$ERROR NTFS" 10 75; bailout; }
+		mount -o remount,rw "$DIRECTORY"
+		KNOPPIXSH="$DIRECTORY/knoppix.sh"
+		writescript "$KNOPPIXSH"
+		;;
 esac
 
 gpid=""
 
-gauge(){
-status=0
-while [ ! -e "$TMP.done" ]; do echo "$status" ; status="`expr \( 100 - $status \) / 4 + $status`"; sleep 2; done | $DIALOG --title "$TITLE1" --gauge "$MESSAGE3" 8 65 0
+gauge() {
+	status=0
+	while [ ! -e "$TMP.done" ]; do echo "$status" ; status="`expr \( 100 - $status \) / 4 + $status`"; sleep 2; done | $DIALOG --title "$TITLE1" --gauge "$MESSAGE3" 8 65 0
 }
 
 # Start status bar
@@ -196,9 +213,9 @@ touch "$TMP"
 IGNORE='/etc/ioctl.save|/etc/mtab'
 
 if [ -n "$SAVEETC" -a -d ${FLL_MOUNTPOINT}/etc ]; then
-findchanged /etc ${FLL_MOUNTPOINT}/etc >>"$TMP"
-[ -n "$SAVENET" ] || IGNORE="$IGNORE|$NETFILES"
-[ -n "$SAVEX" ] || IGNORE="$IGNORE|$XFILES"
+	findchanged /etc ${FLL_MOUNTPOINT}/etc >>"$TMP"
+	[ -n "$SAVENET" ] || IGNORE="$IGNORE|$NETFILES"
+	[ -n "$SAVEX" ] || IGNORE="$IGNORE|$XFILES"
 fi
 
 rm -f "$TMP.tmp"
@@ -212,12 +229,20 @@ STARTCUPS=""
 REINIT=""
 
 while read i; do
-case "$i" in
-/etc/network/interfaces) STARTNET="yes";;
-/etc/pcmcia/*) STARTPCMCIA="yes";;
-/etc/cups*) STARTCUPS="yes";;
-/etc/inittab) REINIT="yes";;
-esac
+	case "$i" in
+		/etc/network/interfaces)
+			STARTNET="yes"
+			;;
+		/etc/pcmcia/*)
+			STARTPCMCIA="yes"
+			;;
+		/etc/cups*)
+			STARTCUPS="yes"
+			;;
+		/etc/inittab)
+			REINIT="yes"
+			;;
+	esac
 done <"$TMP"
 
 
@@ -226,8 +251,8 @@ done <"$TMP"
 [ -n "$STARTCUPS" ]   && SCRIPTS="$SCRIPTS cupsys"
 
 if [ -n "$SCRIPTS" ]; then
-echo 'echo "[1mStarting daemons...[0m"' >>"$KNOPPIXSH"
-echo "for i in $SCRIPTS; do [ -x /etc/init.d/\$i ] && /etc/init.d/\$i start; done" >>"$KNOPPIXSH"
+	echo 'echo "[1mStarting daemons...[0m"' >>"$KNOPPIXSH"
+	echo "for i in $SCRIPTS; do [ -x /etc/init.d/\$i ] && /etc/init.d/\$i start; done" >>"$KNOPPIXSH"
 fi
 
 [ -n "$REINIT" ] && echo 'echo "[1mReloading INIT.[0m" ; init q' >> "$KNOPPIXSH"
@@ -238,9 +263,9 @@ BZIP2=-9 tar -T - -cpPjf "$DIRECTORY/configs.tbz" <"$TMP" 2>"$TMP.err"
 RC="$?"
 
 if [ "$DIRECTORY" = "$FLOPPYDIR" ]; then
-umountfloppy
+	umountfloppy
 else
-umount "$DIRECTORY"
+	umount "$DIRECTORY"
 fi
 
 BOOTOPT="myconfig=$DIRECTORY"
@@ -279,3 +304,4 @@ touch "$TMP.done" ; wait ; rm -f "$TMP.done"
 [ "$RC" = "0" ] && $DIALOG --title "$TITLE1" --msgbox "$SUCCESS" 12 65 || $DIALOG --title "$TITLE1" --msgbox "$ERROR `cat $TMP.err`" 10 75
 
 bailout
+
